# Используем официальный базовый образ Python с поддержкой CUDA
FROM nvidia/cuda:11.7.1-devel-ubuntu22.04

# Обновите пакеты и установите wget
RUN apt-get update && apt-get install -y wget

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Устанавливаем Python и pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Загрузите файл best_model.pth
RUN wget https://storage.yandexcloud.net/rutube-hack/classifier_model.bin
#COPY classifier_model.bin /app/classifier_model.bin

# Устанавливаем переменные окружения
ENV FORCE_CMAKE="1"
ENV CMAKE_ARGS="-DGGML_CUDA=1"

# Копируем файл зависимостей перед копированием кода, чтобы кешировать этот шаг
COPY requirements.txt /app/requirements.txt

# Устанавливаем Python-зависимости
RUN pip install --no-cache-dir --upgrade pip && \
    pip install -r requirements.txt --no-cache-dir

# Копируем остальные файлы в контейнер
COPY . .

# Открываем порт для API
EXPOSE 5023

# Определяем команду для запуска приложения
CMD ["uvicorn", "classifier_server:app", "--host", "0.0.0.0", "--port", "5023", "--workers", "2"]